version: '3'
volumes:
  pgdata:
  static_files:
services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./projectUI:/projectUI
      - static_files:/static_files
    ports:
      - 8007:8007
    command: gunicorn -w 4 project.wsgi -b 0.0.0.0:8007
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "station_disqus"
      POSTGRES_DB: "station_disqus"
      POSTGRES_PASS: "ddsfgsdh343t4gdfsDS3gfdh"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5434:5432

