# Generated by Django 2.1.5 on 2019-01-28 17:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 28, 17, 5, 58, 196661, tzinfo=utc)),
        ),
    ]
