# Generated by Django 2.1.5 on 2019-01-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190128_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='name',
            new_name='title',
        ),
    ]
