# Generated by Django 2.1.5 on 2019-01-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190128_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='title',
            new_name='name',
        ),
    ]
