# Generated by Django 2.1.5 on 2019-01-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190128_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='infomations',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
