# Generated by Django 2.1.5 on 2019-01-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_campaign_infomations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='infomations',
            field=models.TextField(default='-'),
        ),
    ]
