# Generated by Django 2.1.5 on 2019-02-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190128_1757'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campaign',
            new_name='Group',
        ),
    ]
