# Generated by Django 2.1.5 on 2019-02-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190221_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='proxy',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='type_proxy',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
