# Generated by Django 2.1.5 on 2019-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_item_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='base_get',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
