# Generated by Django 2.1.5 on 2019-02-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190221_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='target',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
