# Generated by Django 2.1.5 on 2019-02-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_item_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notification',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='removed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
