# Generated by Django 2.1.5 on 2019-03-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_item_storage_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='storage_post',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='storage_base',
            field=models.TextField(),
        ),
    ]
